--init brewery location
INSERT INTO ROLES ( ROLE) VALUES ('ADMIN');
INSERT INTO ROLES ( ROLE) VALUES ('USER');

INSERT INTO USERS(USERNAME, PASSWORD, ROLE_ID) VALUES ('ADMINISTRATOR', 'ADMIN', 1);
INSERT INTO USERS(USERNAME, PASSWORD, ROLE_ID) VALUES ('OptimusPrime@transfomers.sb', 'megatron', 2);

INSERT INTO CREDIT_CARDS(CARD_CODE, NAME, EXPIRY_DATE, USER_ID) VALUES ('4929431193277800', 'EMILIANO ECHINOFORA', CURRENT_DATE(), 1);
INSERT INTO CREDIT_CARDS(CARD_CODE, NAME, EXPIRY_DATE, USER_ID) VALUES ('5572507509671633', 'Antony Stark', CURRENT_DATE(), 1);
INSERT INTO CREDIT_CARDS(CARD_CODE, NAME, EXPIRY_DATE, USER_ID) VALUES ('869920997367874', 'The doctor', CURRENT_DATE(), 1);


INSERT INTO CREDIT_CARDS(CARD_CODE, NAME, EXPIRY_DATE, USER_ID) VALUES ('5433809771749330', 'OPTIMUS PRIME', CURRENT_DATE(), 2);
INSERT INTO CREDIT_CARDS(CARD_CODE, NAME, EXPIRY_DATE, USER_ID) VALUES ('4538296241304663', 'Magneto', CURRENT_DATE(), 2);
INSERT INTO CREDIT_CARDS(CARD_CODE, NAME, EXPIRY_DATE, USER_ID) VALUES ('375899968472847', 'Charles Xavier', CURRENT_DATE(), 2);
