drop table credit_cards if exists;

drop table roles if exists;

drop table users if exists;

create table credit_cards (
  id bigint generated by default as identity,
  card_code varchar(16) not null,
  expiry_date date,
  name varchar(255) not null,
  user_id bigint not null,
  primary key (id)
);


create table roles (
  id bigint generated by default as identity,
  role varchar(255) not null,
  primary key (id)
);


create table users (
  id bigint generated by default as identity,
  password varchar(255) not null,
  username varchar(255) not null,
  role_id bigint not null,
  primary key (id)
);


alter table credit_cards
  add constraint UK_tlmswgiangu9gmpvtd8g7nmn2 unique (card_code);


alter table roles
  add constraint UK_g50w4r0ru3g9uf6i6fr4kpro8 unique (role);

alter table users
  add constraint UK_r43af9ap4edm43mmtq01oddj6 unique (username);

alter table credit_cards
  add constraint FKn1thfi0pev97g7g4oreo6g4yw
foreign key (user_id)
references users;

alter table users
  add constraint FKp56c1712k691lhsyewcssf40f
foreign key (role_id)
references roles;